@startuml test

hide circle
hide empty members
hide empty methods

skinparam classAttributeIconSize 0

skinparam roundcorner 5

skinparam class {
	BackgroundColor AliceBlue
	BorderColor DarkSlateGray
	ArrowColor Black
	FontColor Black
	FontSize 12
	FontName Helvetica
}

skinparam arrow {
    MessageAlign center
}

Class Company {
	-name :String
	--

	 }
		 
Class Employee {
	-name : String
	--

}
	
Class Vehicle {
	-registration number : String
	--

}	

Class Truck {
	-mass : int
	--

}

Class Car {
	-transmission : String
	--
	
}

Company -- Vehicle : "1"hires"*"

Company -- Employee : "1" employs "*"

Employee -- Vehicle : "1" drives "*"

Vehicle <|--- Truck

Vehicle <|--- Car
 


@enduml
