@startuml test

hide circle
hide empty members
hide empty methods

skinparam classAttributeIconSize 0

skinparam roundcorner 5

skinparam class {
	BackgroundColor AliceBlue
	BorderColor DarkSlateGray
	ArrowColor Black
	FontColor Black
	FontSize 12
	FontName Helvetica
}

skinparam arrow {
    MessageAlign center
}


class Customer {
	+forname : String
	+surname : String
	-password : String
	login(user,pass) 
		
	}

Class Order {

}

Class LineItem {

}

Customer --> Order : orders"*"

Order --> LineItem : " " "0..*"






@enduml
