name: Generate PlantUML Diagrams
on:
  push:
    paths:
      - '**.plantuml'
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
        UML_FILES: ".plantuml"
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed UML files
        id: getfile
        run: |
          git diff-tree -r --no-commit-id --summary ${{ github.sha }} \
          | awk -F' ' '{
            # ensure we are not trying to process deleted files
            # only process puml files
            # do not try to process our theme or custom config
            if ( $1 !~ /^delete$/ && $4 ~ /\.plantuml$/ && $4 !~ /(theme|config)\.plantuml$/ )
            {
              # only print the file name and strip newlines for spaces
              printf "::set-output name=files::" "%s ", $4
            }
          }
          END { print "" } # ensure we do print a newline at the end
          '
      - name: UML files considered echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - name: Generate SVG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tsvg ${{ steps.getfile.outputs.files }}
      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v4.1.2 
        with: 
          commit_user_name: "jmbruel"
          commit_user_email: "jbruel@gmail.com"
          commit_author: "JMB <jbruel@gmail.com>"
          commit_message: "Generate SVG images for PlantUML diagrams" 
          branch: ${{ github.head_ref }}